Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Xy_train_df.to_csv("data/Xy_train.csv",index=False)
Xy_test_df.to_csv("data/Xy_test.csv",index=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-10-3d9a2cb3a9a5>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mXy_train_df[0m[0;34m.[0m[0mto_csv[0m[0;34m([0m[0;34m"data/Xy_train.csv"[0m[0;34m,[0m[0mindex[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mXy_test_df[0m[0;34m.[0m[0mto_csv[0m[0;34m([0m[0;34m"data/Xy_test.csv"[0m[0;34m,[0m[0mindex[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pandas/core/generic.py[0m in [0;36mto_csv[0;34m(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)[0m
[1;32m   3398[0m             [0mdoublequote[0m[0;34m=[0m[0mdoublequote[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3399[0m             [0mescapechar[0m[0;34m=[0m[0mescapechar[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3400[0;31m             [0mstorage_options[0m[0;34m=[0m[0mstorage_options[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3401[0m         )
[1;32m   3402[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pandas/io/formats/format.py[0m in [0;36mto_csv[0;34m(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)[0m
[1;32m   1081[0m             [0mformatter[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mfmt[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1082[0m         )
[0;32m-> 1083[0;31m         [0mcsv_formatter[0m[0;34m.[0m[0msave[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1084[0m [0;34m[0m[0m
[1;32m   1085[0m         [0;32mif[0m [0mcreated_buffer[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pandas/io/formats/csvs.py[0m in [0;36msave[0;34m(self)[0m
[1;32m    232[0m             [0merrors[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0merrors[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    233[0m             [0mcompression[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mcompression[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 234[0;31m             [0mstorage_options[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mstorage_options[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    235[0m         ) as handles:
[1;32m    236[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pandas/io/common.py[0m in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    642[0m                 [0mencoding[0m[0;34m=[0m[0mioargs[0m[0;34m.[0m[0mencoding[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    643[0m                 [0merrors[0m[0;34m=[0m[0merrors[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 644[0;31m                 [0mnewline[0m[0;34m=[0m[0;34m""[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    645[0m             )
[1;32m    646[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/Xy_train.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'data/Xy_train.csv'

